### ISSUE TITLE
gather_licenses does not traverse exports_files

### ISSUE THREAD

**Issue by junglegoog** [bazelbuild/rules_license#107]
`exports_files` declarations should be traversed by the gathering aspect, although they are commonly used to import various licensed resources into build graphs.

Unfortunately, it looks like aspects don't traverse `exports_files` targets at all, as these are not standard bazel rules. Furthermore, `exports_files` also does not supports the `applicable_licenses` attribute.

**Comment by aiuto** [comment]
Adding `applicable_licenses` to `exports_files` is not feasible. We looked and the change is too invasive.
Given that problem, getting the individual files in the aspect gather is not all that useful.

What I recommend is that you create targets that make the files available with filegroup or or a rule that is sementically more meaningful, like a cc_library for a .h file.
