### ISSUE TITLE
Following example in examples/manifest does not work

### ISSUE THREAD

**Issue by pfl** [bazelbuild/rules_license#61]
Trying to apply the license collection mechanism outlined in the examples/manifest directory onto another Bazel based project fails at `load("@rules_license//rules:compliance.bzl", "manifest")` in the WORKSPACE file with error `Error: file '@rules_license//rules:compliance.bzl' does not contain symbol 'manifest'`.

Issuing a `load("@rules_license//rules:license_kind.bzl", "license_kind")` in the same WORKSPACE file works fine, though, so the rules_license http_archive was found and properly loaded.

That same load(...) works when building inside the examples/manifest directory, which makes me suspect the visibility is somewhat wrong or is the examples/manifest something that is meant to be looked at when trying out license collection? Is the proper way to use rules_license in ones own project described somewhere in a way that a novice Bazel user could evaluate its functionality?

**Comment by aiuto** [comment]
That does seem strange. 
TBH, the examples are really out of date and I intend to rewrite them all in Jan and Feb of 2023.

**Comment by aiuto** [comment]
Oddly the manifest example is failing in CI, but works locally.
Since manifest() is really an example and not a supported core features, I have a PR out to move it to the example and out of compliance.bzl

So I'm going to close this as obsolete.
