### ISSUE TITLE
TransitiveLicensesInfo was made private, breaking downstream customers

### ISSUE THREAD

**Issue by junglegoog** [bazelbuild/rules_license#86]
https://github.com/bazelbuild/rules_license/commit/88789cce44d2123f2814cea3c52c87b4d047d05b made TransitiveLicensesInfo private, but that is breaking downstream users of gather_licenses_info.

We need to do that in a soft transition and provide an alternative.

**Comment by aiuto** [comment]
I can to that this time around, but in general files can change location at any of the PRs right now.
The only thing that promises to remain in place for now are license() and license_kind().

**Comment by junglegoog** [comment]
https://github.com/bazelbuild/rules_license/pull/87 has the solution I need for now.

I hope that the move of the gathering rules into its own place can be done in bwd compatible ways too.
